for_window [class=".*"] border pixel 1

default_border pixel 1
default_floating_border pixel 1

client.focused          #368AE3 #000000 #EAEAEA #36E3C2 #368AE3
client.focused_inactive #A636E3 #000000 #EAEAEA #EAEAEA #A636E3
client.unfocused        #000000 #000000 #EAEAEA #FF5A62 #000000
client.urgent           #E3363E #000000 #EAEAEA #E3C236 #E3363E
