# Borda grossa, sem título
default_border pixel 1
default_floating_border pixel 1

# Foco: borda azul elétrico, indicador ciano neon
client.focused          $color4 $bg $fg $color6 $color4
# Inativo: borda magenta, indicador branco suave
client.focused_inactive $color5 $bg $fg $color7 $color5
# Sem foco: borda preta (invisível) + indicador vermelho brilhante (alerta)
client.unfocused        $color0 $bg $fg $color9 $color0
# Urgente: borda vermelho sangue, indicador amarelo ouro
client.urgent           $color1 $bg $fg $color3 $color1
